language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2.1
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_edge.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.0
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: 2.1
      gemfile: gemfiles/activerecord_edge.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/activerecord_edge.gemfile
  allow_failures:
    - rvm: jruby-19mode
    - gemfile: gemfiles/activerecord_edge.gemfile

before_script:
  - "bundle exec rake db:setup PGUSER=postgres"
