language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2

gemfile:
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_edge.gemfile

before_script:
  - "bundle exec rake db:setup POSTGRES_USERNAME=postgres"
